version: "2"
run:
  tests: true
linters:
  enable:
    - asciicheck
    - contextcheck
    - gocritic
    - godot
    - misspell
  disable:
    - forcetypeassert
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/NVIDIA/go-nvlib
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
