// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package info

import (
	"sync"
)

// Ensure, that PropertiesMock does implement Properties.
// If this is not the case, regenerate this file with moq.
var _ Properties = &PropertiesMock{}

// PropertiesMock is a mock implementation of Properties.
//
//	func TestSomethingThatUsesProperties(t *testing.T) {
//
//		// make and configure a mocked Properties
//		mockedProperties := &PropertiesMock{
//			HasDXCoreFunc: func() (bool, string) {
//				panic("mock out the HasDXCore method")
//			},
//			HasNvmlFunc: func() (bool, string) {
//				panic("mock out the HasNvml method")
//			},
//			IsTegraSystemFunc: func() (bool, string) {
//				panic("mock out the IsTegraSystem method")
//			},
//		}
//
//		// use mockedProperties in code that requires Properties
//		// and then make assertions.
//
//	}
type PropertiesMock struct {
	// HasDXCoreFunc mocks the HasDXCore method.
	HasDXCoreFunc func() (bool, string)

	// HasNvmlFunc mocks the HasNvml method.
	HasNvmlFunc func() (bool, string)

	// IsTegraSystemFunc mocks the IsTegraSystem method.
	IsTegraSystemFunc func() (bool, string)

	// calls tracks calls to the methods.
	calls struct {
		// HasDXCore holds details about calls to the HasDXCore method.
		HasDXCore []struct {
		}
		// HasNvml holds details about calls to the HasNvml method.
		HasNvml []struct {
		}
		// IsTegraSystem holds details about calls to the IsTegraSystem method.
		IsTegraSystem []struct {
		}
	}
	lockHasDXCore     sync.RWMutex
	lockHasNvml       sync.RWMutex
	lockIsTegraSystem sync.RWMutex
}

// HasDXCore calls HasDXCoreFunc.
func (mock *PropertiesMock) HasDXCore() (bool, string) {
	callInfo := struct {
	}{}
	mock.lockHasDXCore.Lock()
	mock.calls.HasDXCore = append(mock.calls.HasDXCore, callInfo)
	mock.lockHasDXCore.Unlock()
	if mock.HasDXCoreFunc == nil {
		var (
			bOut bool
			sOut string
		)
		return bOut, sOut
	}
	return mock.HasDXCoreFunc()
}

// HasDXCoreCalls gets all the calls that were made to HasDXCore.
// Check the length with:
//
//	len(mockedProperties.HasDXCoreCalls())
func (mock *PropertiesMock) HasDXCoreCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHasDXCore.RLock()
	calls = mock.calls.HasDXCore
	mock.lockHasDXCore.RUnlock()
	return calls
}

// HasNvml calls HasNvmlFunc.
func (mock *PropertiesMock) HasNvml() (bool, string) {
	callInfo := struct {
	}{}
	mock.lockHasNvml.Lock()
	mock.calls.HasNvml = append(mock.calls.HasNvml, callInfo)
	mock.lockHasNvml.Unlock()
	if mock.HasNvmlFunc == nil {
		var (
			bOut bool
			sOut string
		)
		return bOut, sOut
	}
	return mock.HasNvmlFunc()
}

// HasNvmlCalls gets all the calls that were made to HasNvml.
// Check the length with:
//
//	len(mockedProperties.HasNvmlCalls())
func (mock *PropertiesMock) HasNvmlCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHasNvml.RLock()
	calls = mock.calls.HasNvml
	mock.lockHasNvml.RUnlock()
	return calls
}

// IsTegraSystem calls IsTegraSystemFunc.
func (mock *PropertiesMock) IsTegraSystem() (bool, string) {
	callInfo := struct {
	}{}
	mock.lockIsTegraSystem.Lock()
	mock.calls.IsTegraSystem = append(mock.calls.IsTegraSystem, callInfo)
	mock.lockIsTegraSystem.Unlock()
	if mock.IsTegraSystemFunc == nil {
		var (
			bOut bool
			sOut string
		)
		return bOut, sOut
	}
	return mock.IsTegraSystemFunc()
}

// IsTegraSystemCalls gets all the calls that were made to IsTegraSystem.
// Check the length with:
//
//	len(mockedProperties.IsTegraSystemCalls())
func (mock *PropertiesMock) IsTegraSystemCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockIsTegraSystem.RLock()
	calls = mock.calls.IsTegraSystem
	mock.lockIsTegraSystem.RUnlock()
	return calls
}
